# Form implementation generated from reading ui file 'C:\Users\Asus\Downloads\LTI_Normal\hyperlink_app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import webbrowser
import subprocess
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.open_custom_url)
        self.verticalLayout.addWidget(self.pushButton_5)

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_file_explorer)
        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.open_word)
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.open_canva)
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.open_arduino)  
        self.verticalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Web Browser"))
        self.lineEdit.setText(_translate("Form", "Masukkan URL atau nama situs"))
        self.pushButton_5.setText(_translate("Form", "GO"))
        self.label.setText(_translate("Form", "Klik tombol untuk membuka situs web:"))
        self.pushButton.setText(_translate("Form", "File Explorer"))
        self.pushButton_4.setText(_translate("Form", "Word"))
        self.pushButton_2.setText(_translate("Form", "Canva"))
        self.pushButton_3.setText(_translate("Form", "Arduino IDE"))  

    def open_file_explorer(self):
        try:
            if sys.platform == "win32":  
                subprocess.run(["explorer"])  
            elif sys.platform == "darwin":  
                subprocess.run(["open", "/"])  
            else:  
                subprocess.run(["xdg-open", "/"])  
        except Exception as e:
            self.label.setText(f"Error: {str(e)}")

    def open_word(self):
        
        word_path = r'C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE'
        try:
            subprocess.run([word_path], check=True)  
        except subprocess.CalledProcessError as e:
            self.label.setText(f"Error membuka Word: {str(e)}")
        except FileNotFoundError as e:
            self.label.setText("Microsoft Word tidak ditemukan!")
        except Exception as e:
            self.label.setText(f"Error: {str(e)}")

    def open_canva(self):
        
        canva_path = r'C:\Users\Asus\AppData\Local\Programs\Canva\Canva.exe'
        try:
            subprocess.run([canva_path], check=True)
        except subprocess.CalledProcessError as e:
            self.label.setText(f"Error membuka Canva: {str(e)}")
        except FileNotFoundError as e:
            self.label.setText("Canva tidak ditemukan!")
        except Exception as e:
            self.label.setText(f"Error: {str(e)}")

    def open_custom_url(self):
        url = self.lineEdit.text()
        if url:
            webbrowser.open(url)
        else:
            self.label.setText("URL tidak valid!")

    def open_arduino(self):
        
        arduino_path = r'C:\Users\Asus\AppData\Local\Programs\Arduino IDE\Arduino IDE.exe'
        try:
            subprocess.run([arduino_path], check=True)
        except subprocess.CalledProcessError as e:
            self.label.setText(f"Error membuka Arduino IDE: {str(e)}")
        except FileNotFoundError as e:
            self.label.setText("Arduino IDE tidak ditemukan!")
        except Exception as e:
            self.label.setText(f"Error: {str(e)}")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())

